### ISSUE TITLE
README.md сделать отступы в примерах

### ISSUE THREAD

**Issue by chemt** [aishek/modulargrid#4]
В описании неправильно показан код примеров.

В маркдауне код выделяется пробелами с начала строки, и желательно отделить его пустыми строками до и после

Хотелосьбы видеть примеры такими

```
ModularGrid.init( {
 grid: {
     width: 640,
     vDivisions: 3,
     gutter: 32,
     prependGutter: true,
     appendGutter: true
  }
} ); 
```

**Comment by aishek** [comment]
С удовольствием приму пулл-реквест :)

**Comment by aishek** [comment]
Спасибо большое!
