### ISSUE TITLE
TypeError: target_sizes is undefined

### ISSUE THREAD

**Issue by ivangretsky** [aishek/modulargrid#8]
Good day!
I included this to the end of my page hoping to adjust vertical columns.
```
	<script type="text/javascript" src="modulargrid_debug.js"></script>
	<script>
		ModularGrid.init(
			{
				grid: {
					width: 1200,
					vDivisions: 12,
					gutter: 30,
					prependGutter: true,
					appendGutter: true
				}
			}
		);
	</script>
```
But I get a `TypeError: target_sizes is undefined` error. Am I doing something wrong or is it a bug?

**Comment by aishek** [comment]
Soory for long time to answer. I think it's because of really bad readme. You need also specify image to show:

```
		image: {
			src: 'http://example.com/design.png',
			width: 960,
			height: 1200
		}
```
